name: Build and deploy Vite React to Azure Web App - InnvoiaFrontend

on:
  push:
    branches: [ Deploy-Innovia ]  # Din branch
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: FrontEnd/vite-project  # Ändra till din frontend-folder om den är annorlunda

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build (Vite)
        env:
          VITE_API_URL: innoviahubtuva-debdbqgjg9bjaafh.swedencentral-01.azurewebsites.net
        run: |
          npm ci
          npm run build

      - name: Add SPA web.config (IIS rewrite)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          @"
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="SPA Fallback" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/index.html" />
                  </rule>
                </rules>
              </rewrite>
              <staticContent>
                <remove fileExtension=".json" />
                <mimeMap fileExtension=".json" mimeType="application/json" />
              </staticContent>
            </system.webServer>
          </configuration>
          "@ | Out-File -FilePath dist/web.config -Encoding utf8

      - name: Upload artifact (dist only)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: FrontEnd/vite-project/dist  # Se till att path stämmer med din build-folder

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3A1E271178AB4CFC82C5C106E86E5E76 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA0F5D363C3F473F9403D3A3CE990657 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5F8E415C43E447178BD61433EB44CCC7 }}

      - name: Deploy to Azure Web App (dist/)
        uses: azure/webapps-deploy@v3
        with:
          app-name: InnvoiaFrontend
          slot-name: Production
          package: dist

          
